// Code generated by enum generator; DO NOT EDIT.
package style

import (
	"fmt"
	"strings"
)

// StyleKey is the exported type for the enum
type StyleKey struct {
	name  string
	value int
}

func (e StyleKey) String() string { return e.name }

// Index returns the underlying integer value
func (e StyleKey) Index() int { return e.value }

// MarshalText implements encoding.TextMarshaler
func (e StyleKey) MarshalText() ([]byte, error) {
	return []byte(e.name), nil
}

// UnmarshalText implements encoding.TextUnmarshaler
func (e *StyleKey) UnmarshalText(text []byte) error {
	var err error
	*e, err = ParseStyleKey(string(text))
	return err
}

// _styleKeyParseMap is used for efficient string to enum conversion
var _styleKeyParseMap = map[string]StyleKey{
	"unknown":               StyleKeyUnknown,
	"lineadd":               StyleKeyLineAdd,
	"lineremove":            StyleKeyLineRemove,
	"linecontext":           StyleKeyLineContext,
	"linemodify":            StyleKeyLineModify,
	"lineaddhighlight":      StyleKeyLineAddHighlight,
	"lineremovehighlight":   StyleKeyLineRemoveHighlight,
	"linecontexthighlight":  StyleKeyLineContextHighlight,
	"linemodifyhighlight":   StyleKeyLineModifyHighlight,
	"linenumber":            StyleKeyLineNumber,
	"treepane":              StyleKeyTreePane,
	"treepaneactive":        StyleKeyTreePaneActive,
	"diffpane":              StyleKeyDiffPane,
	"diffpaneactive":        StyleKeyDiffPaneActive,
	"direntry":              StyleKeyDirEntry,
	"fileentry":             StyleKeyFileEntry,
	"fileselected":          StyleKeyFileSelected,
	"annotationmark":        StyleKeyAnnotationMark,
	"reviewedmark":          StyleKeyReviewedMark,
	"statusadded":           StyleKeyStatusAdded,
	"statusdeleted":         StyleKeyStatusDeleted,
	"statusuntracked":       StyleKeyStatusUntracked,
	"statusdefault":         StyleKeyStatusDefault,
	"statusbar":             StyleKeyStatusBar,
	"searchmatch":           StyleKeySearchMatch,
	"annotinputtext":        StyleKeyAnnotInputText,
	"annotinputplaceholder": StyleKeyAnnotInputPlaceholder,
	"annotinputcursor":      StyleKeyAnnotInputCursor,
	"annotlistborder":       StyleKeyAnnotListBorder,
	"helpbox":               StyleKeyHelpBox,
	"themeselectbox":        StyleKeyThemeSelectBox,
	"themeselectboxfocused": StyleKeyThemeSelectBoxFocused,
	"filepickerbox":         StyleKeyFilePickerBox,
	"infobox":               StyleKeyInfoBox,
}

// ParseStyleKey converts string to styleKey enum value.
// Parsing is always case-insensitive.
func ParseStyleKey(v string) (StyleKey, error) {
	if val, ok := _styleKeyParseMap[strings.ToLower(v)]; ok {
		return val, nil
	}
	return StyleKey{}, fmt.Errorf("invalid styleKey: %s", v)
}

// MustStyleKey is like ParseStyleKey but panics if string is invalid
func MustStyleKey(v string) StyleKey {
	r, err := ParseStyleKey(v)
	if err != nil {
		panic(err)
	}
	return r
}

// Public constants for styleKey values
var (
	StyleKeyUnknown = StyleKey{name: "Unknown", value: 0}
	// diff line styles
	StyleKeyLineAdd              = StyleKey{name: "LineAdd", value: 1}
	StyleKeyLineRemove           = StyleKey{name: "LineRemove", value: 2}
	StyleKeyLineContext          = StyleKey{name: "LineContext", value: 3}
	StyleKeyLineModify           = StyleKey{name: "LineModify", value: 4}
	StyleKeyLineAddHighlight     = StyleKey{name: "LineAddHighlight", value: 5}
	StyleKeyLineRemoveHighlight  = StyleKey{name: "LineRemoveHighlight", value: 6}
	StyleKeyLineContextHighlight = StyleKey{name: "LineContextHighlight", value: 7}
	StyleKeyLineModifyHighlight  = StyleKey{name: "LineModifyHighlight", value: 8}
	StyleKeyLineNumber           = StyleKey{name: "LineNumber", value: 9}
	// pane styles
	StyleKeyTreePane       = StyleKey{name: "TreePane", value: 10}
	StyleKeyTreePaneActive = StyleKey{name: "TreePaneActive", value: 11}
	StyleKeyDiffPane       = StyleKey{name: "DiffPane", value: 12}
	StyleKeyDiffPaneActive = StyleKey{name: "DiffPaneActive", value: 13}
	// file tree entry styles
	StyleKeyDirEntry       = StyleKey{name: "DirEntry", value: 14}
	StyleKeyFileEntry      = StyleKey{name: "FileEntry", value: 15}
	StyleKeyFileSelected   = StyleKey{name: "FileSelected", value: 16}
	StyleKeyAnnotationMark = StyleKey{name: "AnnotationMark", value: 17}
	StyleKeyReviewedMark   = StyleKey{name: "ReviewedMark", value: 18}
	// file status styles
	StyleKeyStatusAdded     = StyleKey{name: "StatusAdded", value: 19}
	StyleKeyStatusDeleted   = StyleKey{name: "StatusDeleted", value: 20}
	StyleKeyStatusUntracked = StyleKey{name: "StatusUntracked", value: 21}
	StyleKeyStatusDefault   = StyleKey{name: "StatusDefault", value: 22}
	// chrome styles
	StyleKeyStatusBar   = StyleKey{name: "StatusBar", value: 23}
	StyleKeySearchMatch = StyleKey{name: "SearchMatch", value: 24}
	// ti.TextStyle / ti.PromptStyle in newAnnotationInput
	StyleKeyAnnotInputText = StyleKey{name: "AnnotInputText", value: 25}
	// ti.PlaceholderStyle
	StyleKeyAnnotInputPlaceholder = StyleKey{name: "AnnotInputPlaceholder", value: 26}
	// ti.Cursor.Style / ti.Cursor.TextStyle
	StyleKeyAnnotInputCursor = StyleKey{name: "AnnotInputCursor", value: 27}
	// annotation list popup border
	StyleKeyAnnotListBorder = StyleKey{name: "AnnotListBorder", value: 28}
	// help overlay box
	StyleKeyHelpBox = StyleKey{name: "HelpBox", value: 29}
	// theme selector box
	StyleKeyThemeSelectBox = StyleKey{name: "ThemeSelectBox", value: 30}
	// theme selector focused state
	StyleKeyThemeSelectBoxFocused = StyleKey{name: "ThemeSelectBoxFocused", value: 31}
	// file picker box
	StyleKeyFilePickerBox = StyleKey{name: "FilePickerBox", value: 32}
	// info overlay box (description + session metadata + commits)
	StyleKeyInfoBox = StyleKey{name: "InfoBox", value: 33}
)

// StyleKeyValues contains all possible enum values
var StyleKeyValues = []StyleKey{
	StyleKeyUnknown,
	StyleKeyLineAdd,
	StyleKeyLineRemove,
	StyleKeyLineContext,
	StyleKeyLineModify,
	StyleKeyLineAddHighlight,
	StyleKeyLineRemoveHighlight,
	StyleKeyLineContextHighlight,
	StyleKeyLineModifyHighlight,
	StyleKeyLineNumber,
	StyleKeyTreePane,
	StyleKeyTreePaneActive,
	StyleKeyDiffPane,
	StyleKeyDiffPaneActive,
	StyleKeyDirEntry,
	StyleKeyFileEntry,
	StyleKeyFileSelected,
	StyleKeyAnnotationMark,
	StyleKeyReviewedMark,
	StyleKeyStatusAdded,
	StyleKeyStatusDeleted,
	StyleKeyStatusUntracked,
	StyleKeyStatusDefault,
	StyleKeyStatusBar,
	StyleKeySearchMatch,
	StyleKeyAnnotInputText,
	StyleKeyAnnotInputPlaceholder,
	StyleKeyAnnotInputCursor,
	StyleKeyAnnotListBorder,
	StyleKeyHelpBox,
	StyleKeyThemeSelectBox,
	StyleKeyThemeSelectBoxFocused,
	StyleKeyFilePickerBox,
	StyleKeyInfoBox,
}

// StyleKeyNames contains all possible enum names
var StyleKeyNames = []string{
	"Unknown",
	"LineAdd",
	"LineRemove",
	"LineContext",
	"LineModify",
	"LineAddHighlight",
	"LineRemoveHighlight",
	"LineContextHighlight",
	"LineModifyHighlight",
	"LineNumber",
	"TreePane",
	"TreePaneActive",
	"DiffPane",
	"DiffPaneActive",
	"DirEntry",
	"FileEntry",
	"FileSelected",
	"AnnotationMark",
	"ReviewedMark",
	"StatusAdded",
	"StatusDeleted",
	"StatusUntracked",
	"StatusDefault",
	"StatusBar",
	"SearchMatch",
	"AnnotInputText",
	"AnnotInputPlaceholder",
	"AnnotInputCursor",
	"AnnotListBorder",
	"HelpBox",
	"ThemeSelectBox",
	"ThemeSelectBoxFocused",
	"FilePickerBox",
	"InfoBox",
}

// StyleKeyIter returns a function compatible with Go 1.23's range-over-func syntax.
// It yields all StyleKey values in declaration order. Example:
//
//	for v := range StyleKeyIter() {
//	    // use v
//	}
func StyleKeyIter() func(yield func(StyleKey) bool) {
	return func(yield func(StyleKey) bool) {
		for _, v := range StyleKeyValues {
			if !yield(v) {
				break
			}
		}
	}
}

// These variables are used to prevent the compiler from reporting unused errors
// for the original enum constants. They are intentionally placed in a var block
// that is compiled away by the Go compiler.
var _ = func() bool {
	var _ styleKey = styleKey(0)
	// This avoids "defined but not used" linter error for styleKeyUnknown
	var _ styleKey = styleKeyUnknown
	// This avoids "defined but not used" linter error for styleKeyLineAdd
	var _ styleKey = styleKeyLineAdd
	// This avoids "defined but not used" linter error for styleKeyLineRemove
	var _ styleKey = styleKeyLineRemove
	// This avoids "defined but not used" linter error for styleKeyLineContext
	var _ styleKey = styleKeyLineContext
	// This avoids "defined but not used" linter error for styleKeyLineModify
	var _ styleKey = styleKeyLineModify
	// This avoids "defined but not used" linter error for styleKeyLineAddHighlight
	var _ styleKey = styleKeyLineAddHighlight
	// This avoids "defined but not used" linter error for styleKeyLineRemoveHighlight
	var _ styleKey = styleKeyLineRemoveHighlight
	// This avoids "defined but not used" linter error for styleKeyLineContextHighlight
	var _ styleKey = styleKeyLineContextHighlight
	// This avoids "defined but not used" linter error for styleKeyLineModifyHighlight
	var _ styleKey = styleKeyLineModifyHighlight
	// This avoids "defined but not used" linter error for styleKeyLineNumber
	var _ styleKey = styleKeyLineNumber
	// This avoids "defined but not used" linter error for styleKeyTreePane
	var _ styleKey = styleKeyTreePane
	// This avoids "defined but not used" linter error for styleKeyTreePaneActive
	var _ styleKey = styleKeyTreePaneActive
	// This avoids "defined but not used" linter error for styleKeyDiffPane
	var _ styleKey = styleKeyDiffPane
	// This avoids "defined but not used" linter error for styleKeyDiffPaneActive
	var _ styleKey = styleKeyDiffPaneActive
	// This avoids "defined but not used" linter error for styleKeyDirEntry
	var _ styleKey = styleKeyDirEntry
	// This avoids "defined but not used" linter error for styleKeyFileEntry
	var _ styleKey = styleKeyFileEntry
	// This avoids "defined but not used" linter error for styleKeyFileSelected
	var _ styleKey = styleKeyFileSelected
	// This avoids "defined but not used" linter error for styleKeyAnnotationMark
	var _ styleKey = styleKeyAnnotationMark
	// This avoids "defined but not used" linter error for styleKeyReviewedMark
	var _ styleKey = styleKeyReviewedMark
	// This avoids "defined but not used" linter error for styleKeyStatusAdded
	var _ styleKey = styleKeyStatusAdded
	// This avoids "defined but not used" linter error for styleKeyStatusDeleted
	var _ styleKey = styleKeyStatusDeleted
	// This avoids "defined but not used" linter error for styleKeyStatusUntracked
	var _ styleKey = styleKeyStatusUntracked
	// This avoids "defined but not used" linter error for styleKeyStatusDefault
	var _ styleKey = styleKeyStatusDefault
	// This avoids "defined but not used" linter error for styleKeyStatusBar
	var _ styleKey = styleKeyStatusBar
	// This avoids "defined but not used" linter error for styleKeySearchMatch
	var _ styleKey = styleKeySearchMatch
	// This avoids "defined but not used" linter error for styleKeyAnnotInputText
	var _ styleKey = styleKeyAnnotInputText
	// This avoids "defined but not used" linter error for styleKeyAnnotInputPlaceholder
	var _ styleKey = styleKeyAnnotInputPlaceholder
	// This avoids "defined but not used" linter error for styleKeyAnnotInputCursor
	var _ styleKey = styleKeyAnnotInputCursor
	// This avoids "defined but not used" linter error for styleKeyAnnotListBorder
	var _ styleKey = styleKeyAnnotListBorder
	// This avoids "defined but not used" linter error for styleKeyHelpBox
	var _ styleKey = styleKeyHelpBox
	// This avoids "defined but not used" linter error for styleKeyThemeSelectBox
	var _ styleKey = styleKeyThemeSelectBox
	// This avoids "defined but not used" linter error for styleKeyThemeSelectBoxFocused
	var _ styleKey = styleKeyThemeSelectBoxFocused
	// This avoids "defined but not used" linter error for styleKeyFilePickerBox
	var _ styleKey = styleKeyFilePickerBox
	// This avoids "defined but not used" linter error for styleKeyInfoBox
	var _ styleKey = styleKeyInfoBox
	return true
}()
